[theme]
# Color used for almost all text - Warm Dark Brown
textColor = '#5D4E37'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"